version: '3'
services:
    web:
        build: .
        ports: 
            - "4200:4200"
        volumes:
            - "/app/node_modules" 
            - ".:/app"

# docker-compose exec web ng generate component xyz